# Generated by Django 5.2.17 on 2026-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=11, unique=True, verbose_name='YouTube 影片 ID')),
                ('video_title', models.CharField(max_length=500, verbose_name='影片標題')),
                ('video_author_name', models.CharField(blank=True, max_length=255, verbose_name='影片作者')),
                ('video_thumbnail_url', models.URLField(blank=True, max_length=2048, verbose_name='影片縮圖網址')),
                ('video_view_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='觀看數')),
                ('video_comment_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='留言數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '影片',
                'verbose_name_plural': '影片',
                'ordering': ['-updated_at'],
            },
        ),
    ]
