# Generated by Django 5.2.17 on 2026-08-31 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任務 ID')),
                ('data_source', models.CharField(choices=[('selenium', 'Selenium'), ('youtube_api', 'YouTube API')], default='selenium', max_length=20, verbose_name='資料來源')),
                ('status', models.CharField(choices=[('pending', '等待處理'), ('running', '執行中'), ('awaiting_analysis', '等待 AI 分析'), ('completed', '已完成'), ('failed', '執行失敗'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=30, verbose_name='任務狀態')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='目前進度百分比')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_jobs', to='analyses.video', verbose_name='影片')),
            ],
            options={
                'verbose_name': '分析任務',
                'verbose_name_plural': '分析任務',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='analysis_job_progress_percentage_range')],
            },
        ),
    ]
