# Generated by Django 5.2.17 on 2026-08-31 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysisjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='抓取紀錄 ID')),
                ('data_source', models.CharField(choices=[('selenium', 'Selenium'), ('youtube_api', 'YouTube API')], max_length=20, verbose_name='資料來源')),
                ('status', models.CharField(choices=[('pending', '等待處理'), ('running', '抓取中'), ('completed', '抓取完成'), ('failed', '抓取失敗'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='抓取狀態')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='第幾次抓取')),
                ('fetched_comment_count', models.PositiveIntegerField(default=0, verbose_name='已取得留言數')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='錯誤代碼')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_runs', to='analyses.analysisjob', verbose_name='分析任務')),
            ],
            options={
                'verbose_name': '留言抓取紀錄',
                'verbose_name_plural': '留言抓取紀錄',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('analysis_job', 'attempt_number'), name='unique_fetch_attempt_per_analysis_job'), models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='fetch_run_attempt_number_gte_1')],
            },
        ),
    ]
