# Generated by Django 5.2.17 on 2026-09-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_fetchrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_comment_id', models.CharField(max_length=255, unique=True, verbose_name='YouTube 留言 ID')),
                ('author_display_name', models.CharField(blank=True, max_length=255, verbose_name='留言作者名稱')),
                ('author_channel_id', models.CharField(blank=True, max_length=255, verbose_name='留言作者頻道 ID')),
                ('author_channel_url', models.URLField(blank=True, max_length=2048, verbose_name='留言作者頻道網址')),
                ('comment_text', models.TextField(verbose_name='留言內容')),
                ('like_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='按讚數')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='YouTube 發布時間')),
                ('published_time_text', models.CharField(blank=True, max_length=255, verbose_name='YouTube 顯示時間文字')),
                ('youtube_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='YouTube 更新時間')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置頂')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='analyses.comment', verbose_name='父留言')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='analyses.video', verbose_name='影片')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['published_at', 'created_at'],
            },
        ),
    ]
