# Generated by Django 5.2.17 on 2026-09-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_author_display_name', models.CharField(blank=True, max_length=255, verbose_name='抓取時的留言作者名稱')),
                ('observed_comment_text', models.TextField(verbose_name='抓取時的留言內容')),
                ('observed_like_count', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='抓取時的按讚數')),
                ('observed_published_time_text', models.CharField(blank=True, max_length=255, verbose_name='抓取時的顯示時間文字')),
                ('observed_youtube_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='抓取時的 YouTube 更新時間')),
                ('observed_is_pinned', models.BooleanField(default=False, verbose_name='抓取時是否置頂')),
                ('observed_at', models.DateTimeField(auto_now_add=True, verbose_name='觀察時間')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='analyses.comment', verbose_name='留言')),
                ('fetch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_observations', to='analyses.fetchrun', verbose_name='留言抓取紀錄')),
            ],
            options={
                'verbose_name': '留言觀察紀錄',
                'verbose_name_plural': '留言觀察紀錄',
                'ordering': ['observed_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('fetch_run', 'comment'), name='unique_comment_observation_per_fetch_run')],
            },
        ),
    ]
