# Generated by Django 5.2.17 on 2026-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_commentobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_youtube_comment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='父留言的 YouTube 留言 ID'),
        ),
    ]
