# Generated by Django 5.2.17 on 2026-09-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0006_comment_parent_youtube_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='current_stage',
            field=models.CharField(choices=[('video_confirmation', '確認影片資料'), ('comment_fetching', '抓取留言'), ('comment_normalization', '留言清理與正規化'), ('ai_analysis', 'AI 情緒與主題分析'), ('report_generation', '建立洞察報告')], db_index=True, default='comment_fetching', max_length=30, verbose_name='目前分析階段'),
        ),
    ]
