# Generated by Django 5.2.17 on 2026-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0007_analysisjob_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_like_count',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='按讚數'),
        ),
    ]
