# Generated by Django 5.2.17 on 2026-09-03 15:50

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0008_video_video_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='分析結果 ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='第幾次分析')),
                ('provider_name', models.CharField(max_length=50, verbose_name='AI Provider')),
                ('model_name', models.CharField(max_length=100, verbose_name='AI 模型')),
                ('prompt_version', models.CharField(max_length=100, verbose_name='Prompt 版本')),
                ('schema_version', models.CharField(max_length=100, verbose_name='輸出 Schema 版本')),
                ('analysis_mode', models.CharField(choices=[('small', '小型樣本'), ('medium', '中型樣本'), ('large', '大型樣本')], max_length=20, verbose_name='分析模式')),
                ('analyzed_comment_count', models.PositiveIntegerField(default=0, verbose_name='分析留言數')),
                ('top_level_comment_count', models.PositiveIntegerField(default=0, verbose_name='主留言數')),
                ('reply_comment_count', models.PositiveIntegerField(default=0, verbose_name='回覆數')),
                ('result_data', models.JSONField(default=dict, verbose_name='結構化分析結果')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='輸入 Token 數')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='輸出 Token 數')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='總 Token 數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='analyses.analysisjob', verbose_name='分析任務')),
                ('source_fetch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='analyses.fetchrun', verbose_name='來源抓取紀錄')),
            ],
            options={
                'verbose_name': 'AI 分析結果',
                'verbose_name_plural': 'AI 分析結果',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('analysis_job', 'attempt_number'), name='unique_analysis_attempt_per_job'), models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='analysis_result_attempt_number_gte_1'), models.CheckConstraint(condition=models.Q(('analyzed_comment_count', django.db.models.expressions.CombinedExpression(models.F('top_level_comment_count'), '+', models.F('reply_comment_count')))), name='analysis_result_comment_counts_match')],
            },
        ),
    ]
